// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjESwnZAqWTwFP_U2KjnSfuF_T-hRc2pY',
    appId: '1:1012069754938:android:11444e136d3872b88bad03',
    messagingSenderId: '1012069754938',
    projectId: 'appixo',
    storageBucket: 'appixo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyU1dy2XbzGWpU7_R7Rgu_U1SJO0gXsE4',
    appId: '1:482025845866:ios:cbc7b9e18dd708af5d8613',
    messagingSenderId: '482025845866',
    projectId: 'pgroomapp-e7b8c',
    databaseURL: 'https://pgroomapp-e7b8c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pgroomapp-e7b8c.appspot.com',
    androidClientId: '482025845866-hst64ut2u3jn7ib0thne9qa05vkrqmab.apps.googleusercontent.com',
    iosClientId: '482025845866-3m64h5vb05n2j489h5d747jt2tv25k92.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahumanish.pgroom',
  );
}